// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // GameObject
global.__objectDepths[1] = 0; // FollowMouse
global.__objectDepths[2] = 0; // OutsideDestroy
global.__objectDepths[3] = 0; // MovementExt
global.__objectDepths[4] = 0; // FollowObject
global.__objectDepths[5] = 0; // TrackAngle
global.__objectDepths[6] = 0; // CirclePattern
global.__objectDepths[7] = 0; // NWayPattern
global.__objectDepths[8] = 0; // NWayRandomPattern
global.__objectDepths[9] = 0; // CascadeDestroy
global.__objectDepths[10] = 0; // Lifespan
global.__objectDepths[11] = 0; // InsideRoom
global.__objectDepths[12] = 0; // OnDestroy
global.__objectDepths[13] = 0; // AngleMatchDirection
global.__objectDepths[14] = 0; // DirectionMouse
global.__objectDepths[15] = 0; // Command
global.__objectDepths[16] = 0; // Spawner
global.__objectDepths[17] = 0; // ShootControl
global.__objectDepths[18] = 0; // Shooter
global.__objectDepths[19] = 0; // UFOMove
global.__objectDepths[20] = 0; // MoveControl
global.__objectDepths[21] = 0; // WaterlineDrawer
global.__objectDepths[22] = 0; // WaterlineCollision
global.__objectDepths[23] = 0; // AmmoShootControl
global.__objectDepths[24] = 0; // TrailDrawer
global.__objectDepths[25] = 0; // FadeDrawer
global.__objectDepths[26] = 0; // ExplosionLogic
global.__objectDepths[27] = 0; // GameRestarter
global.__objectDepths[28] = 0; // HighScoreDrawer
global.__objectDepths[29] = 0; // BGMLooper
global.__objectDepths[30] = 0; // WeirdWarhead
global.__objectDepths[31] = 0; // RandomMissileGenerate
global.__objectDepths[32] = 0; // DifficultyModify
global.__objectDepths[33] = 0; // OnClick
global.__objectDepths[34] = 0; // ButtonDrawer
global.__objectDepths[35] = 0; // BombingRun
global.__objectDepths[36] = 0; // CameraFollow
global.__objectDepths[37] = 0; // ProjectileDrawer
global.__objectDepths[38] = 0; // TagLaser
global.__objectDepths[39] = 0; // PointerState
global.__objectDepths[40] = 0; // FireParticle
global.__objectDepths[41] = 0; // GUIDrawer
global.__objectDepths[42] = 0; // BannerDrawer
global.__objectDepths[43] = 0; // StateTracker
global.__objectDepths[44] = 0; // Observable
global.__objectDepths[45] = 0; // BonusDrop
global.__objectDepths[46] = 0; // ExplosionOnDestroy
global.__objectDepths[47] = 0; // ShotDelay
global.__objectDepths[48] = 0; // CollisionHP
global.__objectDepths[49] = 0; // WeirdMaster
global.__objectDepths[50] = 0; // MissileHPIndicator
global.__objectDepths[51] = 0; // CollisionWaterline
global.__objectDepths[52] = 0; // BonusMovement
global.__objectDepths[53] = 0; // GameOverDetector
global.__objectDepths[54] = 0; // Cheater
global.__objectDepths[55] = 0; // Camera
global.__objectDepths[56] = 0; // DifficultyTracker
global.__objectDepths[57] = 0; // Particle
global.__objectDepths[58] = 0; // DisplayManager
global.__objectDepths[59] = 0; // MouseController
global.__objectDepths[60] = 0; // GameController
global.__objectDepths[61] = 0; // ColliderEnemy
global.__objectDepths[62] = 0; // ColliderPlayer
global.__objectDepths[63] = 0; // ColliderPlayerShot
global.__objectDepths[64] = 0; // ColliderScene
global.__objectDepths[65] = 0; // ColliderExplosion
global.__objectDepths[66] = 0; // ColliderSurfaceExplosion
global.__objectDepths[67] = 0; // ColliderBonus
global.__objectDepths[68] = 0; // ColliderDrainer
global.__objectDepths[69] = 0; // Building
global.__objectDepths[70] = 0; // Menu
global.__objectDepths[71] = 0; // MenuItem
global.__objectDepths[72] = 0; // Infrastructure
global.__objectDepths[73] = 0; // NextButton
global.__objectDepths[74] = 0; // Cloud


global.__objectNames[0] = "GameObject";
global.__objectNames[1] = "FollowMouse";
global.__objectNames[2] = "OutsideDestroy";
global.__objectNames[3] = "MovementExt";
global.__objectNames[4] = "FollowObject";
global.__objectNames[5] = "TrackAngle";
global.__objectNames[6] = "CirclePattern";
global.__objectNames[7] = "NWayPattern";
global.__objectNames[8] = "NWayRandomPattern";
global.__objectNames[9] = "CascadeDestroy";
global.__objectNames[10] = "Lifespan";
global.__objectNames[11] = "InsideRoom";
global.__objectNames[12] = "OnDestroy";
global.__objectNames[13] = "AngleMatchDirection";
global.__objectNames[14] = "DirectionMouse";
global.__objectNames[15] = "Command";
global.__objectNames[16] = "Spawner";
global.__objectNames[17] = "ShootControl";
global.__objectNames[18] = "Shooter";
global.__objectNames[19] = "UFOMove";
global.__objectNames[20] = "MoveControl";
global.__objectNames[21] = "WaterlineDrawer";
global.__objectNames[22] = "WaterlineCollision";
global.__objectNames[23] = "AmmoShootControl";
global.__objectNames[24] = "TrailDrawer";
global.__objectNames[25] = "FadeDrawer";
global.__objectNames[26] = "ExplosionLogic";
global.__objectNames[27] = "GameRestarter";
global.__objectNames[28] = "HighScoreDrawer";
global.__objectNames[29] = "BGMLooper";
global.__objectNames[30] = "WeirdWarhead";
global.__objectNames[31] = "RandomMissileGenerate";
global.__objectNames[32] = "DifficultyModify";
global.__objectNames[33] = "OnClick";
global.__objectNames[34] = "ButtonDrawer";
global.__objectNames[35] = "BombingRun";
global.__objectNames[36] = "CameraFollow";
global.__objectNames[37] = "ProjectileDrawer";
global.__objectNames[38] = "TagLaser";
global.__objectNames[39] = "PointerState";
global.__objectNames[40] = "FireParticle";
global.__objectNames[41] = "GUIDrawer";
global.__objectNames[42] = "BannerDrawer";
global.__objectNames[43] = "StateTracker";
global.__objectNames[44] = "Observable";
global.__objectNames[45] = "BonusDrop";
global.__objectNames[46] = "ExplosionOnDestroy";
global.__objectNames[47] = "ShotDelay";
global.__objectNames[48] = "CollisionHP";
global.__objectNames[49] = "WeirdMaster";
global.__objectNames[50] = "MissileHPIndicator";
global.__objectNames[51] = "CollisionWaterline";
global.__objectNames[52] = "BonusMovement";
global.__objectNames[53] = "GameOverDetector";
global.__objectNames[54] = "Cheater";
global.__objectNames[55] = "Camera";
global.__objectNames[56] = "DifficultyTracker";
global.__objectNames[57] = "Particle";
global.__objectNames[58] = "DisplayManager";
global.__objectNames[59] = "MouseController";
global.__objectNames[60] = "GameController";
global.__objectNames[61] = "ColliderEnemy";
global.__objectNames[62] = "ColliderPlayer";
global.__objectNames[63] = "ColliderPlayerShot";
global.__objectNames[64] = "ColliderScene";
global.__objectNames[65] = "ColliderExplosion";
global.__objectNames[66] = "ColliderSurfaceExplosion";
global.__objectNames[67] = "ColliderBonus";
global.__objectNames[68] = "ColliderDrainer";
global.__objectNames[69] = "Building";
global.__objectNames[70] = "Menu";
global.__objectNames[71] = "MenuItem";
global.__objectNames[72] = "Infrastructure";
global.__objectNames[73] = "NextButton";
global.__objectNames[74] = "Cloud";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for